api/urls.py
from django.conf.urls import url, patterns

urlpatterns = patterns('api.views', 
    (r'^businesses/?$', 'get_businesses'),
    (r'^businesses/map/?$', 'get_businesses_map'),

   # (r'^businesses/search/?$', 'search_businesses'),

    (r'^businesses/query/(?P<oid>\d+)/?$', 'query_businesses'),

    (r'^business/(?P<oid>\d+)/?$', 'get_business'),
    (r'^business/add/?$', 'add_business'),
    (r'^business/remove/(?P<oid>\d+)/?$', 'remove_business'),
    (r'^business/edit/(?P<oid>\d+)/?$', 'edit_business'),
    (r'^business/rate/(?P<oid>\d+)/?$', 'rate_business'),
    
    #returns the categories associated  with a business
    (r'^business/topics/(?P<oid>\d+)/?$', 'get_business_topics'),
    (r'^business/topic/(?P<oid>\d+)/?$', 'get_business_topic'),
    (r'^business/topic/add/(?P<oid>\d+)/?$', 'add_business_topic'),
    (r'^business/topic/remove/(?P<oid>\d+)/?$', 'remove_business_topic'),
    (r'^business/topic/rate/(?P<oid>\d+)/?$', 'rate_business_topic'),


    (r'^business/reviews/(?P<oid>\d+)/?$','get_business_reviews'),

    (r'^business/types/(?P<oid>\d+)/?$', 'get_business_types'),
    (r'^business/type/add/(?P<oid>\d+)/?$', 'add_business_type'),
    (r'^business/type/remove/(?P<oid>\d+)/?$', 'remove_business_topic'),
    
    (r'^types/?', 'get_types'),
    (r'^type/add/?', 'add_type'),
    (r'^type/(?P<oid>\d+)/?', 'get_type'),

    
    (r'^all_topics/?$', 'get_topics'),
    (r'^topics/?$', 'get_topics_parent'),
    (r'^topic/(?P<oid>\d+)/?$', 'get_topic'),
    (r'^topic/subscribe/(?P<oid>\d+)/?$', 'subscribe_topic'),
    (r'^topic/unsubscribe/(?P<oid>\d+)/?$', 'unsubscribe_topic'),
    (r'^topics/?$', 'get_topics'),
    (r'^topic/(?P<oid>\d+)/?$', 'get_topic'),
    #(r'^topic/add/?$', 'add_topic'),

    (r'^comment/(?P<oid>\d+)/?$', 'get_comment'),
    (r'^comments/(?P<oid>\d+)/?$', 'get_comments'),
    (r'^comment/add/(?P<oid>\d+)/?$', 'add_comment'),
    (r'^comment/rate/(?P<oid>\d+)/?$', 'rate_comment'),
    (r'^review/edit/(?P<oid>\d+)/?$', 'edit_main_review'),

    (r'^review/(?P<oid>\d+)/?$', 'get_review'),


    
    url(r'^photos/all/?$', 'get_all_photos'),
    (r'^photos/(?P<oid>\d+)/?$', 'get_photos'),
    (r'^photo/(?P<oid>\d+)/?$', 'get_photo'),
    (r'^photo/add/?$', 'add_photo'),
    (r'^photo/remove/(?P<oid>\d+)/?$', 'remove_photo'),
    (r'^photo/edit/(?P<oid>\d+)/?$', 'edit_photo'),
    (r'^photo/rate/(?P<oid>\d+)/?$', 'rate_photo'),

    (r'^query/base/?$', 'get_query_base'),
    (r'^queries/?$', 'get_queries'),
    (r'^query/(?P<oid>\d+)/?$', 'get_query'),
    (r'^query/remove/(?P<oid>\d+)/?$', 'get_query'),
    (r'^query/add/?$', 'add_query'),
    (r'^query/edit/(?P<oid>\d+)/?$', 'edit_query'), 



    (r'^user/?$', 'get_user'),
    (r'^users/?$', 'get_users'),
    (r'^user/update/?$', 'update_user'),
    (r'^user/update/picture/?$', 'update_user_picture')




)

as2/urls.py
from as2 import settings
from django.conf.urls import url, patterns, include
from django.contrib import admin
from wiki.urls import get_pattern as get_wiki_pattern
from as2.settings import STATIC_URL
from coming_soon.views import survey_detail
admin.autodiscover()
urlpatterns = patterns('',
        url(r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', {'url': STATIC_URL+'img/favicon.ico'}),
                url(r'^admin/', include(admin.site.urls)),
        
        url(r'^/?', include('coming_soon.urls')),
        url(r'^/?', include('menu.urls')),
        url(r'^api/', include('api.urls')),
        url(r'^surveys/', include('survey.urls')),
        (r'^accounts/', include('registration.backends.simple.urls')),
        (r'^wiki/?', get_wiki_pattern()),
    
)
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve',  {'document_root':     settings.MEDIA_ROOT}),
		(r'^(?P<path>.*)$', 'django.views.static.serve',  {'document_root':     settings.MEDIA_ROOT}),
    )

wiki/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import patterns, url, include

from wiki.views import article, accounts
from wiki.conf import settings
from wiki.core.plugins import registry

urlpatterns = patterns('',
    url('^$', article.ArticleView.as_view(), name='root', kwargs={'path': ''}),   
    url('^create-root/$', 'wiki.views.article.root_create', name='root_create'),   
    url('^_search/$', article.SearchView.as_view(), name='search'),   
    url('^_revision/diff/(?P<revision_id>\d+)/$', 'wiki.views.article.diff', name='diff'),
)

urlpatterns += patterns('',
    url('^_accounts/sign-up/$', accounts.Signup.as_view(), name='signup'),   
    url('^_accounts/logout/$', accounts.Logout.as_view(), name='logout'),   
    url('^_accounts/login/$', accounts.Login.as_view(), name='login'),   
)

urlpatterns += patterns('',
    # This one doesn't work because it don't know where to redirect after...   
    url('^_revision/change/(?P<article_id>\d+)/(?P<revision_id>\d+)/$', 'wiki.views.article.change_revision', name='change_revision'),   
    url('^_revision/preview/(?P<article_id>\d+)/$', article.Preview.as_view(), name='preview_revision'),   
    url('^_revision/merge/(?P<article_id>\d+)/(?P<revision_id>\d+)/preview/$', 'wiki.views.article.merge', name='merge_revision_preview', kwargs={'preview': True}),   
    
    # Paths decided by article_ids
    url('^(?P<article_id>\d+)/$', article.ArticleView.as_view(), name='get'),   
    url('^(?P<article_id>\d+)/delete/$', article.Delete.as_view(), name='delete'),   
    url('^(?P<article_id>\d+)/deleted/$', article.Deleted.as_view(), name='deleted'),   
    url('^(?P<article_id>\d+)/edit/$', article.Edit.as_view(), name='edit'),   
    url('^(?P<article_id>\d+)/preview/$', article.Preview.as_view(), name='preview'),   
    url('^(?P<article_id>\d+)/history/$', article.History.as_view(), name='history'),   
    url('^(?P<article_id>\d+)/settings/$', article.Settings.as_view(), name='settings'),   
    url('^(?P<article_id>\d+)/source/$', article.Source.as_view(), name='source'),   
    url('^(?P<article_id>\d+)/revision/change/(?P<revision_id>\d+)/$', 'wiki.views.article.change_revision', name='change_revision'),   
    url('^(?P<article_id>\d+)/revision/merge/(?P<revision_id>\d+)/$', 'wiki.views.article.merge', name='merge_revision'),
    url('^(?P<article_id>\d+)/plugin/(?P<slug>\w+)/$', article.Plugin.as_view(), name='plugin'),

)

for plugin in registry.get_plugins().values():
    slug = getattr(plugin, 'slug', None)
    plugin_urlpatterns = getattr(plugin, 'urlpatterns', None)
    if slug and plugin_urlpatterns:
        urlpatterns += patterns('',
            url('^(?P<article_id>\d+)/plugin/'+slug+'/', include(plugin_urlpatterns)),   
            url('^(?P<path>.+/|)_plugin/'+slug+'/', include(plugin_urlpatterns)),   
        )

urlpatterns += patterns('',
    # Paths decided by URLs
    url('^(?P<path>.+/|)_create/$', article.Create.as_view(), name='create'),   
    url('^(?P<path>.+/|)_delete/$', article.Delete.as_view(), name='delete'),   
    url('^(?P<path>.+/|)_deleted/$', article.Deleted.as_view(), name='deleted'),   
    url('^(?P<path>.+/|)_edit/$', article.Edit.as_view(), name='edit'),   
    url('^(?P<path>.+/|)_preview/$', article.Preview.as_view(), name='preview'),   
    url('^(?P<path>.+/|)_history/$', article.History.as_view(), name='history'),   
    url('^(?P<path>.+/|)_dir/$', article.Dir.as_view(), name='dir'),   
    url('^(?P<path>.+/|)_settings/$', article.Settings.as_view(), name='settings'),   
    url('^(?P<path>.+/|)_source/$', article.Source.as_view(), name='source'),   
    url('^(?P<path>.+/|)_revision/change/(?P<revision_id>\d+)/$', 'wiki.views.article.change_revision', name='change_revision'),   
    url('^(?P<path>.+/|)_revision/merge/(?P<revision_id>\d+)/$', 'wiki.views.article.merge', name='merge_revision'),
    url('^(?P<path>.+/|)_plugin/(?P<slug>\w+)/$', article.Plugin.as_view(), name='plugin'),
    url('^(?P<path>.+/|)$', article.ArticleView.as_view(), name='get'),   
)

def get_pattern(app_name="wiki", namespace="wiki"):
    """Every url resolution takes place as "wiki:view_name".
       You should not attempt to have multiple deployments of the wiki in a
       single Django project.
       https://docs.djangoproject.com/en/dev/topics/http/urls/#topics-http-reversing-url-namespaces
    """
    return urlpatterns, app_name, namespace

wiki/plugins/help/models.py
from django.db import models

# Create your models here.

wiki/plugins/links/models.py
from django.db import models

# Create your models here.

wiki/plugins/help/views.py
# Create your views here.

wiki/plugins/images/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext as _
from django.views.generic.base import RedirectView
from django.views.generic.list import ListView

from wiki.conf import settings as wiki_settings
from wiki.decorators import get_article
from wiki.plugins.images import forms
from wiki.plugins.images import models
from wiki.views.mixins import ArticleMixin
from django.views.generic.edit import FormView


class ImageView(ArticleMixin, ListView):
    
    template_name = 'wiki/plugins/images/index.html'
    allow_empty = True
    context_object_name = 'images'
    paginate_by = 10
    
    @method_decorator(get_article(can_read=True, not_locked=True))
    def dispatch(self, request, article, *args, **kwargs):
        return super(ImageView, self).dispatch(request, article, *args, **kwargs)
    
    def get_queryset(self):
        if (self.article.can_moderate(self.request.user) or
            self.article.can_delete(self.request.user)):
            images = models.Image.objects.filter(article=self.article)
        else:
            images = models.Image.objects.filter(article=self.article,
                                                 current_revision__deleted=False)            
        images.select_related()
        return images
    
    def get_context_data(self, **kwargs):
        kwargs.update(ArticleMixin.get_context_data(self, **kwargs))
        return ListView.get_context_data(self, **kwargs)


class DeleteView(ArticleMixin, RedirectView):
    
    permanent = False
    
    @method_decorator(get_article(can_write=True, not_locked=True))
    def dispatch(self, request, article, *args, **kwargs):
        self.image = get_object_or_404(models.Image, article=article,
                                       id=kwargs.get('image_id', None))
        self.restore = kwargs.get('restore', False)
        return ArticleMixin.dispatch(self, request, article, *args, **kwargs)
    
    def get_redirect_url(self, **kwargs):
        
        new_revision = models.ImageRevision()
        new_revision.inherit_predecessor(self.image)
        new_revision.set_from_request(self.request)
        new_revision.deleted = not self.restore
        new_revision.save()
        self.image.current_revision = new_revision
        self.image.save()
        if self.restore:
            messages.info(self.request, _('%s has been restored') % new_revision.get_filename())
        else:
            messages.info(self.request, _('%s has been marked as deleted') % new_revision.get_filename())
        if self.urlpath:
            return reverse('wiki:images_index', kwargs={'path': self.urlpath.path})
        return reverse('wiki:images_index', kwargs={'article_id': self.article.id})


class PurgeView(ArticleMixin, FormView):
    
    template_name = "wiki/plugins/images/purge.html"
    permanent = False
    form_class = forms.PurgeForm
    
    @method_decorator(get_article(can_write=True, can_moderate=True))
    def dispatch(self, request, article, *args, **kwargs):
        self.image = get_object_or_404(models.Image, article=article,
                                       id=kwargs.get('image_id', None))
        return ArticleMixin.dispatch(self, request, article, *args, **kwargs)
    
    def form_valid(self, form):
        
        for revision in self.image.revision_set.all().select_related("imagerevision"):
            revision.imagerevision.image.delete(save=False)
            revision.imagerevision.delete()
        
        if self.urlpath:
            return redirect('wiki:images_index', path=self.urlpath.path)
        return redirect('wiki:images_index', article_id=self.article_id)
    
    def get_context_data(self, **kwargs):
        kwargs = ArticleMixin.get_context_data(self, **kwargs)
        kwargs.update(FormView.get_context_data(self, **kwargs))
        return kwargs


class RevisionChangeView(ArticleMixin, RedirectView):

    permanent = False
    
    @method_decorator(get_article(can_write=True, not_locked=True))
    def dispatch(self, request, article, *args, **kwargs):
        self.image = get_object_or_404(models.Image, article=article,
                                       id=kwargs.get('image_id', None))
        self.revision = get_object_or_404(models.ImageRevision, plugin__article=article,
                                       id=kwargs.get('rev_id', None))
        return ArticleMixin.dispatch(self, request, article, *args, **kwargs)
    
    def get_redirect_url(self, **kwargs):
        
        self.image.current_revision = self.revision
        self.image.save()
        messages.info(self.request, _('%(file)s has been changed to revision #%(revision)d') %
                      {'file': self.image.current_revision.imagerevision.get_filename(),
                       'revision': self.revision.revision_number})
        if self.urlpath:
            return reverse('wiki:images_index', kwargs={'path': self.urlpath.path})
        return reverse('wiki:images_index', kwargs={'article_id': self.article.id})


class RevisionAddView(ArticleMixin, FormView):
    
    template_name = "wiki/plugins/images/revision_add.html"
    form_class = forms.RevisionForm
    
    @method_decorator(get_article(can_write=True, not_locked=True))
    def dispatch(self, request, article, *args, **kwargs):
        self.image = get_object_or_404(models.Image, article=article,
                                       id=kwargs.get('image_id', None))
        if not self.image.can_write(user=request.user):
            return redirect(wiki_settings.LOGIN_URL)
        return ArticleMixin.dispatch(self, request, article, *args, **kwargs)
    
    def get_form_kwargs(self, **kwargs):
        kwargs = super(RevisionAddView, self).get_form_kwargs(**kwargs)
        kwargs['image'] = self.image
        kwargs['request'] = self.request
        return kwargs
    
    def get_context_data(self, **kwargs):
        kwargs = super(RevisionAddView, self).get_context_data(**kwargs)
        kwargs['image'] = self.image
        return kwargs
    
    def form_valid(self, form, **kwargs):
        form.save()
        messages.info(self.request, _('%(file)s has been saved.') %
                      {'file': self.image.current_revision.imagerevision.get_filename(),
                       })
        if self.urlpath:
            return redirect('wiki:edit', path=self.urlpath.path)
        return redirect('wiki:edit', article_id=self.article.id)

wiki/plugins/links/views.py
from wiki.decorators import json_view, get_article
from django.views.generic.base import View
from django.utils.decorators import method_decorator

class QueryUrlPath(View):
    
    # TODO: get_article does not actually support JSON responses
    @method_decorator(json_view)
    @method_decorator(get_article(can_read=True))
    def dispatch(self, request, article, *args, **kwargs):
        max_num = kwargs.pop('max_num', 20)
        # TODO: Move this import when circularity issue is resolved
        # https://github.com/benjaoming/django-wiki/issues/23
        from wiki import models
        query = request.GET.get('query', None)
        
        if query:
            matches = models.URLPath.objects.can_read(request.user).active().filter(
                article__current_revision__title__contains=query,
                article__current_revision__deleted=False,
            )
            matches = matches.select_related_common()
            return [("[%s](wiki:%s)") % (m.article.current_revision.title, '/'+m.path.strip("/")) for m in matches[:max_num]]
        
        return []

wiki/plugins/notifications/views.py
# Create your views here.

wiki/views/mixins.py
from django.views.generic.base import TemplateResponseMixin

from wiki.core.plugins import registry
from wiki.conf import settings

class ArticleMixin(TemplateResponseMixin):
    """A mixin that receives an article object as a parameter (usually from a wiki
    decorator) and puts this information as an instance attribute and in the
    template context."""
    
    def dispatch(self, request, article, *args, **kwargs):
        self.urlpath = kwargs.pop('urlpath', None)
        self.article = article        
        self.children_slice = []
        if settings.SHOW_MAX_CHILDREN > 0:
            for child in self.article.get_children(max_num=settings.SHOW_MAX_CHILDREN+1,
                                                   articles__article__current_revision__deleted=False,
                                                   user_can_read=request.user):
                self.children_slice.append(child)
        return super(ArticleMixin, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        kwargs['urlpath'] = self.urlpath
        kwargs['article'] = self.article
        kwargs['article_tabs'] = registry.get_article_tabs()
        kwargs['children_slice'] = self.children_slice[:20]
        kwargs['children_slice_more'] = len(self.children_slice) > 20
        kwargs['plugins'] = registry.get_plugins()

        return kwargs

templates/wiki/includes/anonymous_blocked.html
{% load i18n %}
{% load url from future %}
<em>
{% url 'wiki:signup' as signup_url %}
{% url 'wiki:login' as login_url %}
{% if login_url and signup_url %}
  {% blocktrans %}
  You need to <a href="{{ login_url }}">log in</a> or <a href="{{ signup_url }}">sign up</a> to use this function.
  {% endblocktrans %}
{% else %}
  {% trans "You need to log in og sign up to use this function." %}
{% endif %}
</em>

templates/wiki/includes/article_menu.html
{% load i18n wiki_tags %}{% load url from future %}

{% with selected_tab as selected %}

<li class="pull-right{% if selected == "settings" %} active{% endif %}">
  {% if not user.is_anonymous %}
  <a href="{% url 'wiki:settings' article_id=article.id path=urlpath.path %}">
    <span class="icon-wrench"></span>
    {% trans "Settings" %}
  </a>
  {% endif %}
</li>

{% for plugin in article_tabs %}
  <li class="pull-right{% if selected == plugin.slug %} active{% endif %}">
    <a href="{% url 'wiki:plugin' slug=plugin.slug article_id=article.id path=urlpath.path %}">
      <span class="{{ plugin.article_tab.1 }}"></span>
      {{ plugin.article_tab.0 }}
    </a>
  </li>
{% endfor %}

<li class="pull-right{% if selected == "history" %} active{% endif %}">
  <a href="{% url 'wiki:history' article_id=article.id path=urlpath.path %}">
    <span class="icon-time"></span>
    {% trans "Changes" %}
  </a>
</li>

{% if article|can_write:user and not article.current_revision.locked %}
<li class="pull-right{% if selected == "edit" %} active{% endif %}">
  <a href="{% url 'wiki:edit' article_id=article.id path=urlpath.path %}">
    <span class="icon-edit"></span>
    {% trans "Edit" %}
  </a>
</li>
{% else %}
<li class="pull-right{% if selected == "source" %} active{% endif %}">
  <a href="{% url 'wiki:source' article_id=article.id path=urlpath.path %}">
    <span class="icon-lock"></span>
    {% trans "View Source" %}
  </a>
</li>
{% endif %}

<li class="pull-right{% if selected == "view" %} active{% endif %}">
  <a href="{% url 'wiki:get' article_id=article.id path=urlpath.path %}">
    <span class="icon-home"></span>
    {% trans "View" %}
  </a>
</li>

{% endwith %}

templates/wiki/includes/breadcrumbs.html
{% load i18n %}{% load url from future %}
{% if urlpath %}
<div id="article-breadcrumbs">

<ul class="breadcrumb pull-left" class="">
  {% for ancestor in urlpath.cached_ancestors %}
    <span class="divider">/</span>
    <li><a href="{% url 'wiki:get' path=ancestor.path %}">{{ ancestor.article.current_revision.title }}</a></li>
  {% endfor %}
  <span class="divider">/</span>
  <li class="active"><a href="{% url 'wiki:get' path=urlpath.path %}">{{ article.current_revision.title }}</a></li>
  <span class="divider">/</span>
</ul>
<div class="pull-left" style="margin-left: 10px;">
  <div class="btn-group">
    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#" style="padding: 7px;" title="{% trans "Sub-articles for" %} {{ article.current_revision.title }}">
      <span class="icon-list"></span>
      <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      {% for child in children_slice %}
        <li>
          <a href="{% url 'wiki:get' path=child.path %}">
            {{ child.article.current_revision.title }}
          </a>
        </li>
        {% empty %}
        <li><a href="#"><em>{% trans "No sub-articles" %}</em></a></li>
      {% endfor %}
      {% if children_slice_more %}
      <li><a href="#"><em>{% trans "...and more" %}</em></a></li>
      {% endif %}
      <li class="divider"></li>
      <li>
        <a href="{% url 'wiki:dir' path=urlpath.path %}">{% trans "Browse articles in this level" %} &raquo;</a>
      </li>
    </ul>
  </div>
</div>
<div class="pull-left" style="margin-left: 10px;">
  <div class="btn-group">
    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#" style="padding: 7px;" title="{% trans "Sub-articles for" %} {{ article.current_revision.title }}">
      <span class="icon-plus"></span>
      <span class="caret"></span>
    </a>    
    <ul class="dropdown-menu">
      <li>
        {% if urlpath.parent %}
        <a href="{% url 'wiki:create' path=urlpath.parent.path %}" style="padding: 7px;">
          <span class="icon-arrow-right"></span>
          {% trans "New article next to" %} {{ article.current_revision.title }}
        </a>
        {% endif %}
        <a href="{% url 'wiki:create' path=urlpath.path %}" style="padding: 7px;">
          <span class="icon-arrow-down"></span>
          {% trans "New article below" %} {{ article.current_revision.title }}
        </a>
      </li>
    </ul>
  </div>
</div>
<div style="clear: both"></div>
</div>
{% endif %}

templates/wiki/includes/editor.html
{% load wiki_tags i18n %}
{% include "wiki/includes/editormedia.html" %}

{% wiki_form form %}
<script language="javascript">
  $(document).ready(function() {
    $("#id_revision").val('{{ article.current_revision.id }}');
  });
</script>

templates/wiki/includes/editor_sidebar.html
<div class="accordion" id="accordion_{{ plugin.slug }}">

{% for plugin, plugin_form in sidebar %}

  <div class="accordion-group">
    
    <div class="accordion-heading">
      <a class="accordion-toggle" href="#collapse_{{ plugin.slug }}" data-toggle="collapse">
        <h3>{{ plugin.sidebar.headline }} <span class="{{ plugin.sidebar.icon_class }}"></span></h3>
      </a>
    </div>
    
    <div id="collapse_{{ plugin.slug }}" class="accordion-body collapse{% if plugin_form.errors %} in{% endif %}">
      <div class="accordion-inner form-vertical">
        {% if plugin.sidebar.template %}
          {% with plugin_form as form and plugin as plugin %}
            <form method="POST" class="form-horizontal" action="?f={{ plugin_form.form_id }}" enctype="multipart/form-data">
              {% csrf_token %}
              {% include plugin.sidebar.template %}
            </form>
          {% endwith %}
        {% endif %}
      </div>
    </div>
  
  </div>
{% endfor %}
</div>

templates/wiki/includes/editormedia.html
{% load sekizai_tags %}
{% addtoblock "js" %}
<script type="text/javascript" src="{{ STATIC_URL }}wiki/js/editor.js"></script>
{% for js in editor.Media.js %}
<script type="text/javascript" src="{{ STATIC_URL }}{{ js }}"></script>
{% endfor %}
{% endaddtoblock %}

{% addtoblock "css" %}
{% for media, srcs in editor.Media.css.items %}
  {% for src in srcs %}
    <link rel="stylesheet" media="{{ media }}" href="{{ STATIC_URL }}{{ src }}" />
  {% endfor %}
{% endfor %}
{% endaddtoblock %}

templates/wiki/includes/form.html
{% csrf_token %}
{% if form.non_field_errors %}
  {% if form_error_title %}<h4 class="alert-heading">{{ form_error_title }}</h4>{% endif %}
  {% for error_message in form.non_field_errors %}
    <div class="alert alert-block alert-error">
      {{ error_message }}
    </div>    
  {% endfor %}
{% endif %}

{% for field in form %}

  {% if field.is_hidden %}
    {{ field }}
  {% else %}

  <div id="div_{{ field.auto_id }}" class="clearfix control-group{% if field.errors %} error{% endif %}">
    {% if field.label %}
      <label for="{{ field.id_for_label }}" class="control-label {% if field.field.required %}requiredField{% endif %}">
      {{ field.label|safe }}
      </label>
    {% endif %}
    <div class="controls">
      {{ field }} {% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
      {% if field.errors %}
        {% for error in field.errors %}
          <div id="error_{{ forloop.counter }}_{{ field.auto_id }}" class="help-block"><strong>{{ error }}</strong></div>
        {% endfor %}
      {% endif %}
      {% if field.help_text %}
        <p id="hint_{{ field.auto_id }}" class="help-block">{{ field.help_text|safe }}</p>
      {% endif %}
    </div>
  </div>
  {% endif %}

{% endfor %}

templates/wiki/includes/pagination.html
{% load i18n %}
{% if is_paginated %}
<div class="pagination">
  <ul>
    {% for pc in paginator.page_range %}
    <li class="{% if pc == page_obj.number %} active{% endif %}"><a href="?page={{ pc }}{% if appended_key %}&{{ appended_key }}={{ appended_value }}{% endif %}">{{ pc }}</a></li>
    {% endfor %}
  </ul>
</div>
{% endif %}

templates/wiki/includes/render.html
{% load wiki_tags i18n cache %}

{% block wiki_contents %}

  {% for plugin in plugins %}
    {% if plugin.RenderMedia.css %}
      {% for media, url in plugin.RenderMedia.css.items %}
        <link rel="stylesheet" href="{{ STATIC_URL }}{{ url }}" />
      {% endfor %}
    {% endif %}
    {% if plugin.RenderMedia.js %}
      {% for url in plugin.RenderMedia.js %}
        <script type="text/javascript" src="{{ STATIC_URL }}{{ url }}"></script>
      {% endfor %}
    {% endif %}
  {% endfor %}
  
  
  <div class="wiki-article">
  {% if not preview %}

    {% if article.current_revision %}
      {% cache 6000 article article.current_revision.id %}
        {{ article.render }}
      {% endcache %}
    {% endif %}

  {% else %}

    {{ content|default:"" }}

  {% endif %}
  </div>
  
{% endblock %}

templates/wiki/includes/revision_info.html
{% comment %}

  This reusable code is shared between different templates and different inheritors of
  BaseRevision.

{% endcomment %}


{% load wiki_tags i18n %}
{% if not hidedate %}{{ revision.created }}{% endif %} {% if not hidenumber %}(#{{ revision.revision_number }}) {% trans "by" %}{% endif %} {% if revision.user %}{{ revision.user }}{% else %}{% if article|can_moderate:user %}{{ revision.ip_address|default:"anonymous (IP not logged)" }}{% else %}{% trans "anonymous (IP logged)" %}{% endif %}{% endif %}
{% if revision == current_revision %}
  <strong>*</strong>
{% endif %}
{% if revision.deleted %}
<span class="badge badge-important">{% trans "deleted" %}</span>
{% endif %}
{% if revision.previous_revision.deleted and not revision.deleted %}
<span class="badge badge-success">{% trans "restored" %}</span>
{% endif %}
{% if revision.locked %}
<span class="badge">{% trans "locked" %}</span>
{% endif %}
{% if revision.previous_revision.locked and not revision.locked %}
<span class="badge">{% trans "unlocked" %}</span>
{% endif %}