api/urls.py
from django.conf.urls import url, patterns

urlpatterns = patterns('api.views', 
    (r'^businesses/?$', 'get_businesses'),
    (r'^businesses/map/?$', 'get_businesses_map'),

   # (r'^businesses/search/?$', 'search_businesses'),

    (r'^businesses/query/(?P<oid>\d+)/?$', 'query_businesses'),

    (r'^business/(?P<oid>\d+)/?$', 'get_business'),
    (r'^business/add/?$', 'add_business'),
    (r'^business/remove/(?P<oid>\d+)/?$', 'remove_business'),
    (r'^business/edit/(?P<oid>\d+)/?$', 'edit_business'),
    (r'^business/rate/(?P<oid>\d+)/?$', 'rate_business'),
    
    #returns the categories associated  with a business
    (r'^business/topics/(?P<oid>\d+)/?$', 'get_business_topics'),
    (r'^business/topic/(?P<oid>\d+)/?$', 'get_business_topic'),
    (r'^business/topic/add/(?P<oid>\d+)/?$', 'add_business_topic'),
    (r'^business/topic/remove/(?P<oid>\d+)/?$', 'remove_business_topic'),
    (r'^business/topic/rate/(?P<oid>\d+)/?$', 'rate_business_topic'),


    (r'^business/reviews/(?P<oid>\d+)/?$','get_business_reviews'),

    (r'^business/types/(?P<oid>\d+)/?$', 'get_business_types'),
    (r'^business/type/add/(?P<oid>\d+)/?$', 'add_business_type'),
    (r'^business/type/remove/(?P<oid>\d+)/?$', 'remove_business_topic'),
    
    (r'^types/?', 'get_types'),
    (r'^type/add/?', 'add_type'),
    (r'^type/(?P<oid>\d+)/?', 'get_type'),

    
    (r'^all_topics/?$', 'get_topics'),
    (r'^topics/?$', 'get_topics_parent'),
    (r'^topic/(?P<oid>\d+)/?$', 'get_topic'),
    (r'^topic/subscribe/(?P<oid>\d+)/?$', 'subscribe_topic'),
    (r'^topic/unsubscribe/(?P<oid>\d+)/?$', 'unsubscribe_topic'),
    (r'^topics/?$', 'get_topics'),
    (r'^topic/(?P<oid>\d+)/?$', 'get_topic'),
    #(r'^topic/add/?$', 'add_topic'),

    (r'^comment/(?P<oid>\d+)/?$', 'get_comment'),
    (r'^comments/(?P<oid>\d+)/?$', 'get_comments'),
    (r'^comment/add/(?P<oid>\d+)/?$', 'add_comment'),
    (r'^comment/rate/(?P<oid>\d+)/?$', 'rate_comment'),
    (r'^review/edit/(?P<oid>\d+)/?$', 'edit_main_review'),

    (r'^review/(?P<oid>\d+)/?$', 'get_review'),


    
    url(r'^photos/all/?$', 'get_all_photos'),
    (r'^photos/(?P<oid>\d+)/?$', 'get_photos'),
    (r'^photo/(?P<oid>\d+)/?$', 'get_photo'),
    (r'^photo/add/?$', 'add_photo'),
    (r'^photo/remove/(?P<oid>\d+)/?$', 'remove_photo'),
    (r'^photo/edit/(?P<oid>\d+)/?$', 'edit_photo'),
    (r'^photo/rate/(?P<oid>\d+)/?$', 'rate_photo'),

    (r'^query/base/?$', 'get_query_base'),
    (r'^queries/?$', 'get_queries'),
    (r'^query/(?P<oid>\d+)/?$', 'get_query'),
    (r'^query/remove/(?P<oid>\d+)/?$', 'get_query'),
    (r'^query/add/?$', 'add_query'),
    (r'^query/edit/(?P<oid>\d+)/?$', 'edit_query'), 



    (r'^user/?$', 'get_user'),
    (r'^users/?$', 'get_users'),
    (r'^user/update/?$', 'update_user'),
    (r'^user/update/picture/?$', 'update_user_picture')




)

as2/urls.py
from as2 import settings
from django.conf.urls import url, patterns, include
from django.contrib import admin
from wiki.urls import get_pattern as get_wiki_pattern
from as2.settings import STATIC_URL
from coming_soon.views import survey_detail
admin.autodiscover()
urlpatterns = patterns('',
        url(r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', {'url': STATIC_URL+'img/favicon.ico'}),
                url(r'^admin/', include(admin.site.urls)),
        
        url(r'^/?', include('coming_soon.urls')),
        url(r'^/?', include('menu.urls')),
        url(r'^api/', include('api.urls')),
        url(r'^surveys/', include('survey.urls')),
        (r'^accounts/', include('registration.backends.simple.urls')),
        (r'^wiki/?', get_wiki_pattern()),
    
)
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve',  {'document_root':     settings.MEDIA_ROOT}),
		(r'^(?P<path>.*)$', 'django.views.static.serve',  {'document_root':     settings.MEDIA_ROOT}),
    )

wiki/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import patterns, url, include

from wiki.views import article, accounts
from wiki.conf import settings
from wiki.core.plugins import registry

urlpatterns = patterns('',
    url('^$', article.ArticleView.as_view(), name='root', kwargs={'path': ''}),   
    url('^create-root/$', 'wiki.views.article.root_create', name='root_create'),   
    url('^_search/$', article.SearchView.as_view(), name='search'),   
    url('^_revision/diff/(?P<revision_id>\d+)/$', 'wiki.views.article.diff', name='diff'),
)

urlpatterns += patterns('',
    url('^_accounts/sign-up/$', accounts.Signup.as_view(), name='signup'),   
    url('^_accounts/logout/$', accounts.Logout.as_view(), name='logout'),   
    url('^_accounts/login/$', accounts.Login.as_view(), name='login'),   
)

urlpatterns += patterns('',
    # This one doesn't work because it don't know where to redirect after...   
    url('^_revision/change/(?P<article_id>\d+)/(?P<revision_id>\d+)/$', 'wiki.views.article.change_revision', name='change_revision'),   
    url('^_revision/preview/(?P<article_id>\d+)/$', article.Preview.as_view(), name='preview_revision'),   
    url('^_revision/merge/(?P<article_id>\d+)/(?P<revision_id>\d+)/preview/$', 'wiki.views.article.merge', name='merge_revision_preview', kwargs={'preview': True}),   
    
    # Paths decided by article_ids
    url('^(?P<article_id>\d+)/$', article.ArticleView.as_view(), name='get'),   
    url('^(?P<article_id>\d+)/delete/$', article.Delete.as_view(), name='delete'),   
    url('^(?P<article_id>\d+)/deleted/$', article.Deleted.as_view(), name='deleted'),   
    url('^(?P<article_id>\d+)/edit/$', article.Edit.as_view(), name='edit'),   
    url('^(?P<article_id>\d+)/preview/$', article.Preview.as_view(), name='preview'),   
    url('^(?P<article_id>\d+)/history/$', article.History.as_view(), name='history'),   
    url('^(?P<article_id>\d+)/settings/$', article.Settings.as_view(), name='settings'),   
    url('^(?P<article_id>\d+)/source/$', article.Source.as_view(), name='source'),   
    url('^(?P<article_id>\d+)/revision/change/(?P<revision_id>\d+)/$', 'wiki.views.article.change_revision', name='change_revision'),   
    url('^(?P<article_id>\d+)/revision/merge/(?P<revision_id>\d+)/$', 'wiki.views.article.merge', name='merge_revision'),
    url('^(?P<article_id>\d+)/plugin/(?P<slug>\w+)/$', article.Plugin.as_view(), name='plugin'),

)

for plugin in registry.get_plugins().values():
    slug = getattr(plugin, 'slug', None)
    plugin_urlpatterns = getattr(plugin, 'urlpatterns', None)
    if slug and plugin_urlpatterns:
        urlpatterns += patterns('',
            url('^(?P<article_id>\d+)/plugin/'+slug+'/', include(plugin_urlpatterns)),   
            url('^(?P<path>.+/|)_plugin/'+slug+'/', include(plugin_urlpatterns)),   
        )

urlpatterns += patterns('',
    # Paths decided by URLs
    url('^(?P<path>.+/|)_create/$', article.Create.as_view(), name='create'),   
    url('^(?P<path>.+/|)_delete/$', article.Delete.as_view(), name='delete'),   
    url('^(?P<path>.+/|)_deleted/$', article.Deleted.as_view(), name='deleted'),   
    url('^(?P<path>.+/|)_edit/$', article.Edit.as_view(), name='edit'),   
    url('^(?P<path>.+/|)_preview/$', article.Preview.as_view(), name='preview'),   
    url('^(?P<path>.+/|)_history/$', article.History.as_view(), name='history'),   
    url('^(?P<path>.+/|)_dir/$', article.Dir.as_view(), name='dir'),   
    url('^(?P<path>.+/|)_settings/$', article.Settings.as_view(), name='settings'),   
    url('^(?P<path>.+/|)_source/$', article.Source.as_view(), name='source'),   
    url('^(?P<path>.+/|)_revision/change/(?P<revision_id>\d+)/$', 'wiki.views.article.change_revision', name='change_revision'),   
    url('^(?P<path>.+/|)_revision/merge/(?P<revision_id>\d+)/$', 'wiki.views.article.merge', name='merge_revision'),
    url('^(?P<path>.+/|)_plugin/(?P<slug>\w+)/$', article.Plugin.as_view(), name='plugin'),
    url('^(?P<path>.+/|)$', article.ArticleView.as_view(), name='get'),   
)

def get_pattern(app_name="wiki", namespace="wiki"):
    """Every url resolution takes place as "wiki:view_name".
       You should not attempt to have multiple deployments of the wiki in a
       single Django project.
       https://docs.djangoproject.com/en/dev/topics/http/urls/#topics-http-reversing-url-namespaces
    """
    return urlpatterns, app_name, namespace

wiki/plugins/attachments/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from . import settings

from wiki import managers
from wiki.models.pluginbase import ReusablePlugin
from wiki.models.article import BaseRevisionMixin

class IllegalFileExtension(Exception):
    """File extension on upload is not allowed"""
    pass

class Attachment(ReusablePlugin):

    objects = managers.ArticleFkManager()

    current_revision = models.OneToOneField('AttachmentRevision', 
                                            verbose_name=_(u'current revision'),
                                            blank=True, null=True, related_name='current_set',
                                            help_text=_(u'The revision of this attachment currently in use (on all articles using the attachment)'),
                                            )
    
    original_filename = models.CharField(max_length=256, verbose_name=_(u'original filename'), blank=True, null=True)

    def can_write(self, **kwargs):
        user = kwargs.get('user', None)
        if not settings.ANONYMOUS and (not user or user.is_anonymous()):
            return False
        return ReusablePlugin.can_write(self, **kwargs)
    
    def can_delete(self, user):
        return self.can_write(user=user)
    
    class Meta:
        verbose_name = _(u'attachment')
        verbose_name_plural = _(u'attachments')
        app_label = settings.APP_LABEL 
    
    def __unicode__(self):
        return "%s: %s" % (self.article.current_revision.title, self.original_filename)    
        
def upload_path(instance, filename):
    from os import path
    try:
        extension = filename.split(".")[-1]
    except IndexError:
        # No extension
        raise IllegalFileExtension("No file extension found in filename. That's not okay!")
    
    # Must be an allowed extension
    if not extension.lower() in map(lambda x: x.lower(), settings.FILE_EXTENSIONS):
        raise IllegalFileExtension("The following filename is illegal: %s. Extension has to be one of %s" % 
                                   (filename, ", ".join(settings.FILE_EXTENSIONS)))

    # Has to match original extension filename
    if instance.id and instance.attachment and instance.attachment.original_filename:
        original_extension = instance.attachment.original_filename.split(".")[-1]
        if not extension.lower() == original_extension:
            raise IllegalFileExtension("File extension has to be '%s', not '%s'." %
                                       (original_extension, extension.lower()))
    elif instance.attachment:
        instance.attachment.original_filename = filename
        
    upload_path = settings.UPLOAD_PATH
    upload_path = upload_path.replace('%aid', str(instance.attachment.article.id))
    if settings.UPLOAD_PATH_OBSCURIFY:
        import random, hashlib
        m=hashlib.md5(str(random.randint(0,100000000000000)))
        upload_path = path.join(upload_path, m.hexdigest())
    return path.join(upload_path, filename + '.upload')


class AttachmentRevision(BaseRevisionMixin, models.Model):
    
    attachment = models.ForeignKey('Attachment')

    file = models.FileField(upload_to=upload_path, #@ReservedAssignment
                            max_length=255,
                            verbose_name=_(u'file'),
                            storage=settings.STORAGE_BACKEND)
        
    description = models.TextField(blank=True)
    
    class Meta:
        verbose_name = _(u'attachment revision')
        verbose_name_plural = _(u'attachment revisions')
        ordering = ('created',)
        get_latest_by = ('revision_number',)
        app_label = settings.APP_LABEL
        
    def get_filename(self):
        """Used to retrieve the filename of a revision.
        But attachment.original_filename should always be used in the frontend
        such that filenames stay consistent."""
        # TODO: Perhaps we can let file names change when files are replaced?
        if not self.file:
            return None
        filename = self.file.name.split("/")[-1]
        return ".".join(filename.split(".")[:-1])
    
    def get_size(self):
        """Used to retrieve the file size and not cause exceptions."""
        try:
            return self.file.size
        except OSError:
            return None
        except ValueError:
            return None
    
    def save(self, *args, **kwargs):
        if (not self.id and
            not self.previous_revision and 
            self.attachment and
            self.attachment.current_revision and 
            self.attachment.current_revision != self):
            
            self.previous_revision = self.attachment.current_revision

        if not self.revision_number:
            try:
                previous_revision = self.attachment.attachmentrevision_set.latest()
                self.revision_number = previous_revision.revision_number + 1
            # NB! The above should not raise the below exception, but somehow it does.
            except AttachmentRevision.DoesNotExist, Attachment.DoesNotExist:
                self.revision_number = 1
        
        super(AttachmentRevision, self).save(*args, **kwargs)
        
        if not self.attachment.current_revision:
            # If I'm saved from Django admin, then article.current_revision is me!
            self.attachment.current_revision = self
            self.attachment.save()

    def __unicode__(self):
        return "%s: %s (r%d)" % (self.attachment.article.current_revision.title, 
                                 self.attachment.original_filename,
                                 self.revision_number)    

wiki/plugins/help/models.py
from django.db import models

# Create your models here.

wiki/plugins/links/models.py
from django.db import models

# Create your models here.

wiki/plugins/attachments/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.utils.translation import ugettext as _

from wiki.plugins.attachments import models

class AttachmentForm(forms.ModelForm):
    
    description = forms.CharField(label=_(u'Description'),
                                  help_text=_(u'A short summary of what the file contains'),
                                  required=False)
    
    class Meta:
        model = models.AttachmentRevision
        fields = ('file', 'description',)

class DeleteForm(forms.Form):
    """This form is both used for dereferencing and deleting attachments"""
    confirm = forms.BooleanField(label=_(u'Yes I am sure...'),
                                 required=False)
    
    def clean_confirm(self):
        if not self.cleaned_data['confirm']:
            raise forms.ValidationError(_(u'You are not sure enough!'))
        return True

class SearchForm(forms.Form):
    
    query = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'search-query'}),)

wiki/plugins/help/views.py
# Create your views here.

wiki/plugins/links/views.py
from wiki.decorators import json_view, get_article
from django.views.generic.base import View
from django.utils.decorators import method_decorator

class QueryUrlPath(View):
    
    # TODO: get_article does not actually support JSON responses
    @method_decorator(json_view)
    @method_decorator(get_article(can_read=True))
    def dispatch(self, request, article, *args, **kwargs):
        max_num = kwargs.pop('max_num', 20)
        # TODO: Move this import when circularity issue is resolved
        # https://github.com/benjaoming/django-wiki/issues/23
        from wiki import models
        query = request.GET.get('query', None)
        
        if query:
            matches = models.URLPath.objects.can_read(request.user).active().filter(
                article__current_revision__title__contains=query,
                article__current_revision__deleted=False,
            )
            matches = matches.select_related_common()
            return [("[%s](wiki:%s)") % (m.article.current_revision.title, '/'+m.path.strip("/")) for m in matches[:max_num]]
        
        return []

wiki/plugins/notifications/views.py
# Create your views here.

wiki/views/mixins.py
from django.views.generic.base import TemplateResponseMixin

from wiki.core.plugins import registry
from wiki.conf import settings

class ArticleMixin(TemplateResponseMixin):
    """A mixin that receives an article object as a parameter (usually from a wiki
    decorator) and puts this information as an instance attribute and in the
    template context."""
    
    def dispatch(self, request, article, *args, **kwargs):
        self.urlpath = kwargs.pop('urlpath', None)
        self.article = article        
        self.children_slice = []
        if settings.SHOW_MAX_CHILDREN > 0:
            for child in self.article.get_children(max_num=settings.SHOW_MAX_CHILDREN+1,
                                                   articles__article__current_revision__deleted=False,
                                                   user_can_read=request.user):
                self.children_slice.append(child)
        return super(ArticleMixin, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        kwargs['urlpath'] = self.urlpath
        kwargs['article'] = self.article
        kwargs['article_tabs'] = registry.get_article_tabs()
        kwargs['children_slice'] = self.children_slice[:20]
        kwargs['children_slice_more'] = len(self.children_slice) > 20
        kwargs['plugins'] = registry.get_plugins()

        return kwargs

templates/wiki/base.html
{% load sekizai_tags i18n %}{% load url from future %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block pagetitle %}{% endblock %} -- django-\/\/  i K |</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="www.django-wiki.org">

    <!-- Le styles -->
    <link href="{{ STATIC_URL }}css/bootstrap.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/bootstrap-responsive.min.css" rel="stylesheet">
    
    <!-- TODO: Put all this stuff in Less -->
    <style media="print">
      .navbar,
      .nav-tabs li a,
      #article-breadcrumbs
      {display: none;}
    </style>
    <style media="all">
      #div_id_title .asteriskField{display:none}
      #id_title {font-size: 20px; height: 30px; padding: 6px; width: 98%;}
      #id_summary {width: 98%; padding: 6px;}
      
      h1#article-title {font-size: 2em; margin-top: -5px;}
      
      #article_edit_form label {max-width: 100px;}
      #article_edit_form .controls {margin-left: 120px;}
      
      .form-horizontal label { font-size: 16px; font-weight: normal; color: #777;}
  
      .settings-form label {min-width: 250px; font-size: inherit; font-weight: normal;}
      .settings-form .controls {margin-left: 270px;}
      .settings-form select {}
      .settings-form .form-actions { padding-left: 270px; }
      
      #attachment_form #id_description
      { width: 95% }
      
      #edit_sidebar .accordion {margin-bottom: 5px;}
      
      .wiki-article div.toc {
        margin: 10px 0;
        background: #f9f9f9;
        padding: 10px;
        width: 300px;
        border: 1px solid #CCC;
      }
            
      .wiki-article a.linknotfound {color: #C87;}
      
      .wiki-article pre {
        max-width: 700px;
      }
      
      input[type=file] {float: none; width: auto;}
      .asteriskField { font-size: 20px; margin-left: 5px;}
      
      .notification-list .since {
        font-size: 80%;
        color: #CCC;
      }
      
      .directory-toolbar .filter-clear { margin-right: 10px; position: relative; top: 5px; }
      
      .accordion-heading h3 {margin: 0;}
      
      .breadcrumb .icon-bar {
          display: block;
          width: 18px;
          height: 2px;
          background-color: rgb(245, 245, 245);
          border-radius: 1px 1px 1px 1px;
          box-shadow: 0px 1px 0px rgba(0, 0, 0, 0.25);
          margin-top: 3px;
      }
      .breadcrumb .icon-bar:first-child{margin-top: 0;}
      
      #navbar_wiki_search input.search-query {width: 80px;}
      
    </style>
    
    <script src="{{ STATIC_URL }}js/wii/jquery.min.js"></script>
    <script src="{{ STATIC_URL }}js/wiki/core.js"></script>
    <script src="{{ STATIC_URL }}js/wiki/bootstrap.min.js"></script>
    {% render_block "css" %}
    {% render_block "js" %}
    
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

  </head>

  <body>

    {% block wiki_body %}
    
    {% block navbar %}
    <div class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="{% url 'wiki:root' %}">django-wiki</a>
          <form class="navbar-search pull-right" id="navbar_wiki_search" method="GET" action="{% url 'wiki:search' %}">
            <span class="icon-search"></span>
            <input type="text" name="query" class="search-query" placeholder="{% trans "Search..." %}" />
          </form>
          <div class="pull-right">
            {% if user.is_authenticated %}
            <ul class="nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <span class="badge notification-cnt">0</span>
                  {{ user }}
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <a href="{% url 'wiki:logout' %}">
                      <span class="icon-off"></span>
                      {% trans "Log out" %}
                    </a>
                  </li>
                  <li class="divider"></li>
                  <div class="notification-list">
                    <div class="notification-li-container"></div>
                    <li class="notifications-empty"><a href="#"><em>{% trans "No notifications" %}</em></a></li>
                    <li class="divider"></li>
                    <li><a href="#" onclick="notify_mark_read()">{% trans "Clear notifications list" %}</a></li>
                  </div>
                </ul>
              </li>
            </ul>
            {% else %}
            <ul class="nav">
              <li>
                <a href="{% url 'wiki:login' %}">{% trans "Log in" %}</a>
              </li>
              <li>
                <a href="{% url 'wiki:signup' %}">{% trans "Sign up" %}</a>
              </li>
            </ul>
            {% endif %}
          </div>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="/">Home</a></li>
              <li><a href="https://github.com/benjaoming/django-wiki" target="_blank">About</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    {% endblock %}

    <div class="container" style="margin-top: 60px;">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">
            <a class="close" data-dismiss="alert" href="#">&times;</a>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      {% block wiki_breadcrumbs %}{% endblock %}
      {% block wiki_contents %}
      <h1>Bootstrap starter template</h1>
      <p>Use this document as a way to quick start any new project.<br> All you get is this message and a barebones HTML document.</p>
      {% endblock %}
      
      <div style="padding: 30px 0;" class="clearfix">
      <footer>
        <hr />
        <a href="https://github.com/benjaoming/django-wiki" class="pull-right"><img src="{{ STATIC_URL }}wiki/img/github_icon.png" /></a>
        {% block footer_prepend %}
        {% endblock %}
        <p>Powered by <a href="http://www.django-wiki.org">django-wiki</a>, an open source application under the <a href="http://www.gnu.org/licenses/quick-guide-gplv3.html">GPLv3</a> license. Let knowledge be the cure.</p>
        <div style="clear: both"></div>
      </footer>
      </div>

    </div> <!-- /container -->

    {% endblock %}

  </body>
</html>

templates/wiki/dir.html
{% extends "wiki/article.html" %}
{% load wiki_tags i18n humanize %}
{% load url from future %}

{% block pagetitle %}{% trans "Listing articles in" %} {{ article.current_revision.title }}{% endblock %}

{% block wiki_contents_tab %}

{% url 'wiki:dir' urlpath.path as self_url %}

<form class="form-search directory-toolbar">
<div class="well well-small">
  <div class="btn-group pull-left">
    {% if urlpath.parent %}
    <a href="{% url 'wiki:dir' path=urlpath.parent.path %}" class="btn">
      <span class="icon-arrow-up"></span>
      {% trans "Up one level" %}
    </a>
    {% endif %}
    <a href="{% url 'wiki:create' path=urlpath.path %}" class="btn">
      <span class="icon-plus"></span>
      {% trans "Add article" %}
    </a>
  </div>
  <div class="pull-right">
    {{ filter_form.query }}
  </div>
  {% if filter_query %}
    <div class="pull-right filter-clear">
      <a href="{{ self_url }}">({% trans "clear" %})</a>
    </div>
  {% endif %}

  <div class="clearfix"></div>
</div>
</form>

<p>
  {% with paginator.object_list.count as cnt %}
    {% blocktrans with urlpath.path as path and cnt|pluralize:_("article,articles") as articles_plur and cnt|pluralize:_("is,are") as articles_plur_verb %}
      Browsing <strong><a href="{{ self_url }}">/{{ path }}</a></strong>. There {{ articles_plur_verb }} <strong>{{ cnt }} {{ articles_plur }}</strong> in this level.
    {% endblocktrans %}
  {% endwith %}
</p>

<table class="table table-striped">
  <tr>
    <th>{% trans "Title" %}</th>
    <th>{% trans "Slug" %}</th>
    <th>{% trans "Last modified" %}</th>
  </tr>
  {% for urlpath in directory %}
    <tr>
      <td>
        <a href="{% url 'wiki:get' path=urlpath.path %}"> {{ urlpath.article.current_revision.title }} </a> 
        <a href="{% url 'wiki:dir' path=urlpath.path %}" class="list-children"> › </a>
        {% if urlpath.article.current_revision.deleted %}
          <span class="icon-trash"></span>
        {% endif %}
        {% if urlpath.article.current_revision.locked %}
          <span class="icon-lock"></span>
        {% endif %}
      </td>
      <td>
        {{ urlpath.slug }}
      </td>
      <td>
        {{ urlpath.article.current_revision.created|naturaltime }}
      </td>
    </tr>
    {% empty%}
    <tr>
      <td colspan="100">
        <em>{% trans "There are no articles in this level" %}</em>
      </td>
    </tr>
  {% endfor %}
</table>

{% include "wiki/includes/pagination.html" %}

{% endblock %}

templates/wiki/error.html
{% extends "wiki/base.html" %}
{% load wiki_tags i18n %}
{% load url from future %}

{% block pagetitle %}{{ article.current_revision.title }}{% endblock %}

{% block wiki_breadcrumbs %}
{% include "wiki/includes/breadcrumbs.html" %}
{% endblock %}

{% block wiki_contents %}

{% if error_type == "ancestors_missing" %}

  <div class="missing">
    <p>This article was not found, and neither was its parent article. <a href="{% url 'wiki:get' path='' %}">Go to the main wiki article</a></p>
  </div>
  
{% else %}  

  <div class="error">
    <p>There was some sort of error accessing this page. Sorry!</p>
  </div>

{% endif %}

{% endblock %}